- name: Install Python
  yum:
    name: ["python36", "gcc", "python3-devel"]
    state: present

- name: Add RoboShop App User
  user:
    name: roboshop

- name: Include AZ CLI Installation Steps
  include_tasks: az-cli-setup.yml

- name: Create Artifact directory
  file:
    path: "{{ARTIFACT_PATH}}"
    state: directory

- name: Include Artifact Download Steps
  include_tasks: artifact-download.yml

- name: Install python requirements
  pip:
    requirements: "{{ARTIFACT_PATH}}/requirements.txt"
    executable: pip3
